version: '3.0'
services:
  patient-a:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.pulse_device
    ports:
      - "9001:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - CONFIG_FILE=hospital_use_case/configA.json
  patient-b:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.pulse_device
    ports:
      - "9002:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - CONFIG_FILE=hospital_use_case/configB.json
  patient-c:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.pulse_device
    ports:
      - "9003:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - CONFIG_FILE=hospital_use_case/configC.json
  taxi-a1:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.taxi_car
    ports:
      - "9101:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - FRIENDLY_NAME=taxi-position-companyA1
      - CONFIG_FILE=taxi_car_use_case/configA1.json
  taxi-a2:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.taxi_car
    ports:
      - "9102:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - FRIENDLY_NAME=taxi-position-companyA2
      - CONFIG_FILE=taxi_car_use_case/configA2.json
  taxi-b1:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.taxi_car
    ports:
      - "9201:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - FRIENDLY_NAME=taxi-position-companyB1
      - CONFIG_FILE=taxi_car_use_case/configB1.json
  taxi-b2:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.taxi_car
    ports:
      - "9202:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - FRIENDLY_NAME=taxi-position-companyB2
      - CONFIG_FILE=taxi_car_use_case/configB2.json
  taxi-c1:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.taxi_car
    ports:
      - "9301:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - FRIENDLY_NAME=taxi-position-companyC1
      - CONFIG_FILE=taxi_car_use_case/configC1.json
  taxi-c2:
    build:
      context: ./python-wot
      dockerfile: Dockerfile.taxi_car
    ports:
      - "9302:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - FRIENDLY_NAME=taxi-position-companyC2
      - CONFIG_FILE=taxi_car_use_case/configC2.json
  node-red:
    image: nodered/node-red
    ports:
    - 2880:1880
    - 2881:1881
    links:
    - patient-a
    - patient-b
    - taxi-a1
    - taxi-a2
    - taxi-b1
    - taxi-b2
    - taxi-c1
    - taxi-c2
    volumes:
    - ./node-red/.node-red:/data
  # mariadb:
  #   image: mariadb
  #   restart: 'no'
  #   environment:
  #     MYSQL_ROOT_PASSWORD: example
  # adminer:
  #   image: adminer
  #   restart: 'no'
  #   ports:
  #     - 9090:8080
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'mongoExample-pwd'
    # ports:
    #   - '172.0.0.0:27017:27017'
    volumes:
      - ./data/mongodb:/data/db
      - ./data/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'mongoExample-pwd'
      ME_CONFIG_BASICAUTH_USERNAME: 'admin'
      ME_CONFIG_BASICAUTH_PASSWORD: 'test-password'
