version: '2.0'
services:
  wot:
    build: ./python-wot
    ports:
    - "8888:8888"
    volumes:
     - ./python-wot:/usr/src/app
  node-red:
    image: nodered/node-red
    ports:
    - 1880:1880
    - 1881:1881
    links:
    - wot
    - thingsboard
    volumes:
    - ./node-red/.node-red:/data
  thingsboard:
    image: thingsboard/tb-postgres
    ports:
    - 9090:9090
    - 1883:1883
    - 5683:5683
    volumes:
    - ./thingsboard/.mytb-data:/data
    - ./thingsboard/.mytb-logs:/var/log/thingsboard
