version: '3.0'
services:
  patient-a:
    build: ./python-wot
    ports:
      - "9001:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - CONFIG_FILE=configA.json
  patient-b:
    build: ./python-wot
    ports:
      - "9002:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - CONFIG_FILE=configB.json
  patient-c:
    build: ./python-wot
    ports:
      - "9003:8888"
    volumes:
      - ./python-wot:/usr/src/app
    environment:
      - CONFIG_FILE=configC.json
  node-red:
    image: nodered/node-red
    ports:
    - 1880:1880
    - 1881:1881
    links:
    - patient-a
    - patient-b
    volumes:
    - ./node-red/.node-red:/data
